### ISSUE TITLE
Vi um problem onde tem as 3 peças douradas juntas.

### ISSUE THREAD

**Issue by tonussi** [automata/board-game#1]
E se o jogador cair em um loop infinito no meio da trilha?

_brincando.._ :cow2:

**Comment by GabiThume** [comment]
:boom:  Ótima pergunta! hahahaha

**Comment by tonussi** [comment]
Interessante que vocês criaram um tabuleiro que pode assumir configurações diferentes. Nunca vi isso num jogo de tabuleiro.
